export default {
  axis: 'x',
  cursorPoint: 'center',
  height: 'auto',
  multiple: false,
  onBegin: (e: any) => null,
  onFinish: (e: any) => null,
  onSlide: (e: any) => null,
  onStart: (e: any) => null,
  onStop: (e: any) => null,
  unit: 'percent',
  width: '100%',
  x: 0,
  y: 0,
};
